### ISSUE TITLE
Use ZeroMQ or any other queue instead of database to queue / dequeue

### ISSUE THREAD

**Issue by natalie-o-perret** [ivanpintar/cqrs-and-event-sourcing-fsharp#1]
Can use ZeroMQ or any other queue instead of pushing pulling on a database to enqueue / dequeue commands.

**Comment by ivanpintar** [comment]
This is a valid point if this were a real project. As this was just a learning project, to get familiar with the concepts of CQRS and ES, I will not bother with a real queuing solution.
